#!/bin/bash
# =============================================================
# ConvertX — Full Setup Script
# Usage: bash setup.sh
# Run from project root
#
# Backing services are AWS-emulated via LocalStack Pro:
#   PostgreSQL → RDS        Redis → ElastiCache
#   Images     → ECR        Logs  → CloudWatch Logs
# =============================================================

set -e

PROJECT_ROOT=$(pwd)

# ── Colors ─────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
err()  { echo -e "  ${RED}✗${NC} $1"; exit 1; }
info() { echo -e "  ${YELLOW}▶${NC} $1"; }

# ── Load .env ──────────────────────────────────────────────────
if [ ! -f .env ]; then
  err ".env file not found. Copy .env.example to .env and fill in your values."
fi

source .env

if [ -z "$POSTGRES_PASSWORD" ]; then
  err "POSTGRES_PASSWORD must be set in .env"
fi
# REDIS_PASSWORD is optional: LocalStack's ElastiCache has no AUTH, so the
# bootstrap does not store one. It is only meaningful against real AWS.

if [ -z "$LOCALSTACK_AUTH_TOKEN" ]; then
  err "LOCALSTACK_AUTH_TOKEN must be set in .env (https://app.localstack.cloud → Auth Token).
     The Pro image will not start without it."
fi

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║       ConvertX — Full Setup              ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Step 1: Namespaces ─────────────────────────────────────────
echo "▶ Step 1: Creating namespaces..."
kubectl apply -f infra/namespace.yaml
ok "Namespaces ready"

# ── Step 2: MetalLB ────────────────────────────────────────────
echo ""
echo "▶ Step 2: Installing MetalLB..."
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml > /dev/null
kubectl wait --namespace metallb-system \
  --for=condition=ready pod \
  --selector=app=metallb \
  --timeout=120s > /dev/null
kubectl apply -f infra/metallb/ip-address-pool.yaml > /dev/null
ok "MetalLB ready"

# ── Step 3: Kong Gateway Operator ─────────────────────────────
echo ""
echo "▶ Step 3: Installing Kong Gateway Operator..."
helm repo add kong https://charts.konghq.com 2>/dev/null || true
helm repo update > /dev/null

if helm status kong-operator -n kong > /dev/null 2>&1; then
  ok "Kong already installed, skipping helm install"
else
  helm install kong-operator kong/gateway-operator \
    -n kong \
    --create-namespace \
    --wait > /dev/null
  ok "Kong Gateway Operator installed"
fi

kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml > /dev/null
kubectl apply -f infra/kong/gateway/gateway.yaml > /dev/null

echo "  Waiting for Kong gateway to be ready..."
for i in {1..30}; do
  STATUS=$(kubectl get gateway convertx-gateway -n kong \
    -o jsonpath='{.status.conditions[?(@.type=="Programmed")].status}' 2>/dev/null)
  if [ "$STATUS" = "True" ]; then
    break
  fi
  sleep 3
done
ok "Kong Gateway ready"

# The dataplane Service name is generated by the operator and changes on every
# reinstall. Resolve it once here: CloudFront needs it as an origin during
# bootstrap, and the port-forward needs it at the end.
echo "  Resolving Kong dataplane service..."
KONG_SVC=""
for i in {1..20}; do
  KONG_SVC=$(kubectl get svc -n kong --no-headers 2>/dev/null \
    | grep "dataplane-ingress" | awk '{print $1}' | head -1)
  if [ -n "$KONG_SVC" ]; then break; fi
  sleep 3
done

if [ -z "$KONG_SVC" ]; then
  err "Could not find Kong dataplane service. Run: kubectl get svc -n kong"
fi
KONG_ORIGIN="$KONG_SVC.kong.svc.cluster.local"
ok "Kong dataplane: $KONG_SVC"

# ── Step 4: LocalStack Pro ─────────────────────────────────────
# Replaces the former Redis and PostgreSQL steps: both now run inside
# LocalStack as ElastiCache and RDS.
echo ""
echo "▶ Step 4: Deploying LocalStack Pro..."
kubectl apply -f infra/localstack/namespace.yaml > /dev/null
kubectl apply -f infra/localstack/pv.yaml > /dev/null
kubectl apply -f infra/localstack/configmap.yaml > /dev/null

sed "s|LOCALSTACK_AUTH_TOKEN_PLACEHOLDER|$LOCALSTACK_AUTH_TOKEN|g" \
  infra/localstack/auth-token-secret.yaml | kubectl apply -f - > /dev/null

kubectl apply -f infra/aws-credentials-secret.yaml > /dev/null
kubectl apply -f infra/localstack/deployment.yaml > /dev/null
kubectl apply -f infra/localstack/service.yaml > /dev/null

# Pro validates its licence on boot, so allow longer than the community image.
# rollout status, not `kubectl wait --selector`: the latter captures the pod
# list when it starts and blocks indefinitely if one of those pods is deleted,
# which the Recreate strategy guarantees on every re-run.
if ! kubectl rollout status deployment/localstack -n localstack \
  --timeout=300s > /dev/null; then
  echo ""
  err "LocalStack Pro did not become ready. Check the licence token:
     kubectl logs -n localstack -l app=localstack --tail=50"
fi
ok "LocalStack Pro ready"

LOCALSTACK_POD=$(kubectl get pod -n localstack -l app=localstack \
  -o jsonpath='{.items[0].metadata.name}')

# ── Step 5: Bootstrap AWS resources ───────────────────────────
echo ""
echo "▶ Step 5: Provisioning AWS resources (RDS, ElastiCache, ECR, Cognito)..."

# ConfigMap is generated from bootstrap.sh so the script has a single source.
kubectl create configmap localstack-bootstrap \
  --from-file=bootstrap.sh=infra/localstack/bootstrap.sh \
  -n localstack --dry-run=client -o yaml | kubectl apply -f - > /dev/null

kubectl delete job localstack-bootstrap -n localstack --ignore-not-found > /dev/null

sed -e "s/REDIS_PWD_PLACEHOLDER/$REDIS_PASSWORD/g" \
    -e "s/POSTGRES_PWD_PLACEHOLDER/$POSTGRES_PASSWORD/g" \
    -e "s/KONG_ORIGIN_PLACEHOLDER/$KONG_ORIGIN/g" \
    infra/localstack/bootstrap-job.yaml | kubectl apply -f - > /dev/null

# RDS and ElastiCache start real postgres/redis processes — this is slow.
if ! kubectl wait --namespace localstack \
  --for=condition=complete job/localstack-bootstrap \
  --timeout=420s > /dev/null; then
  echo ""
  err "Bootstrap job failed. Logs:
     kubectl logs -n localstack job/localstack-bootstrap"
fi
ok "Secrets, RDS, ElastiCache, ECR, buckets and queues created"

# ── Step 6: Resolve dynamic endpoints ─────────────────────────
# RDS/ElastiCache ports are assigned at creation time, so they are read back
# from SecretsManager rather than hardcoded anywhere.
echo ""
echo "▶ Step 6: Resolving service endpoints..."

get_secret() {
  kubectl exec -n localstack "$LOCALSTACK_POD" -- \
    awslocal secretsmanager get-secret-value \
      --secret-id "$1" --query SecretString --output text 2>/dev/null \
    | tr -d '\r\n'
}

DB_ENDPOINT=$(get_secret convertx/postgres/endpoint)
REDIS_ENDPOINT=$(get_secret convertx/redis/endpoint)

if [ -z "$DB_ENDPOINT" ] || [ -z "$REDIS_ENDPOINT" ]; then
  err "Could not read endpoints from SecretsManager.
     kubectl logs -n localstack job/localstack-bootstrap"
fi

REDIS_EP_HOST="${REDIS_ENDPOINT%:*}"
REDIS_EP_PORT="${REDIS_ENDPOINT##*:}"

ok "RDS:         $DB_ENDPOINT"
ok "ElastiCache: $REDIS_ENDPOINT"

# ── Step 7: Build Docker Images ───────────────────────────────
echo ""
echo "▶ Step 7: Building Docker images..."

cd $PROJECT_ROOT/services/auth-service
docker build -t convertx/auth-service:latest . -q > /dev/null
ok "auth-service built"

cd $PROJECT_ROOT/services/golang-conversion-service
docker build -t convertx/conversion-service:latest . -q > /dev/null
ok "conversion-service built"

cd $PROJECT_ROOT

# ECR repositories exist (created by bootstrap) but K8s still pulls locally.
# See scripts/push-to-ecr.sh for the push path and its prerequisites.

# ── Step 8: Deploy Auth Service ───────────────────────────────
echo ""
echo "▶ Step 8: Deploying Auth Service..."
kubectl apply -f services/auth-service/k8s/configmap.yaml > /dev/null
kubectl apply -f services/auth-service/k8s/deployment.yaml > /dev/null
kubectl apply -f services/auth-service/k8s/service.yaml > /dev/null
kubectl apply -f services/auth-service/k8s/httproute.yaml > /dev/null
kubectl apply -f services/auth-service/k8s/hpa.yaml > /dev/null

# Force a fresh pull of :latest and pick up any endpoint changes.
kubectl rollout restart deployment/auth-service -n convertx > /dev/null 2>&1 || true

kubectl rollout status deployment/auth-service -n convertx --timeout=180s > /dev/null
ok "Auth Service ready"

# ── Step 9: Deploy Conversion Service ─────────────────────────
echo ""
echo "▶ Step 9: Deploying Conversion Service..."
kubectl apply -f services/golang-conversion-service/k8s/configmap.yaml > /dev/null
kubectl apply -f services/golang-conversion-service/k8s/deployment.yaml > /dev/null
kubectl apply -f services/golang-conversion-service/k8s/service.yaml > /dev/null
kubectl apply -f services/golang-conversion-service/k8s/httproute.yaml > /dev/null
kubectl apply -f services/golang-conversion-service/k8s/hpa.yaml > /dev/null

kubectl rollout restart deployment/conversion-service -n convertx > /dev/null 2>&1 || true

kubectl rollout status deployment/conversion-service -n convertx --timeout=180s > /dev/null
ok "Conversion Service ready"

# ── Step 10: Kong Plugins ──────────────────────────────────────
echo ""
echo "▶ Step 10: Applying Kong plugins..."

# Kong talks to ElastiCache directly, so it needs the resolved host and port.
# The password comes from SecretsManager rather than .env: LocalStack's
# ElastiCache has no AUTH, and sending a password to a Redis without one is a
# hard error. An empty secret means the password line is removed entirely.
REDIS_SECRET=$(get_secret convertx/redis/password)
if [ -z "$REDIS_SECRET" ]; then
  PW_RULE='/password: REDIS_PASSWORD_PLACEHOLDER/d'
  ok "ElastiCache has no AUTH — omitting password from Kong config"
else
  PW_RULE="s/REDIS_PASSWORD_PLACEHOLDER/$REDIS_SECRET/g"
fi

for PLUGIN in rate-limiting-plugin rate-limiting-registered-plugin; do
  sed -e "s/REDIS_HOST_PLACEHOLDER/$REDIS_EP_HOST/g" \
      -e "s/REDIS_PORT_PLACEHOLDER/$REDIS_EP_PORT/g" \
      -e "$PW_RULE" \
      infra/kong/plugins/$PLUGIN.yaml | kubectl apply -f - > /dev/null
done

kubectl apply -f infra/kong/plugins/cors-plugin.yaml > /dev/null
kubectl apply -f infra/kong/plugins/request-size-plugin.yaml > /dev/null
kubectl apply -f infra/kong/plugins/response-headers-plugin.yaml > /dev/null
kubectl apply -f infra/kong/plugins/request-logging-plugin.yaml > /dev/null
kubectl apply -f infra/kong/plugins/request-id-plugin.yaml > /dev/null

kubectl apply -f infra/kong/plugins/bindings/auth-route-bindings.yaml > /dev/null
kubectl apply -f infra/kong/plugins/bindings/conversion-route-bindings.yaml > /dev/null
ok "Kong plugins applied"

# ── Step 11: Log shipping ──────────────────────────────────────
# fluent-bit runs as a DaemonSet rather than a sidecar: the Kong dataplane pod
# is owned by the Gateway Operator and cannot take an extra container, and a
# node-level collector picks up Kong and both Go services at once.
echo ""
echo "▶ Step 11: Deploying log shipping to CloudWatch..."
kubectl apply -f infra/logging/fluent-bit-configmap.yaml > /dev/null
kubectl apply -f infra/logging/fluent-bit-daemonset.yaml > /dev/null

# Restart to pick up config changes on re-runs (DaemonSets do not roll on
# ConfigMap edits by themselves).
kubectl rollout restart daemonset/fluent-bit -n convertx > /dev/null 2>&1 || true

if kubectl rollout status daemonset/fluent-bit -n convertx --timeout=120s > /dev/null 2>&1; then
  ok "fluent-bit shipping to CloudWatch Logs"
else
  echo -e "  ${YELLOW}!${NC} fluent-bit not ready — logs will not reach CloudWatch"
  echo "     kubectl logs -n convertx -l app=fluent-bit --tail=30"
fi

# ── Step 12: Monitoring + autoscaling ──────────────────────────
# Prometheus discovers targets from the Kubernetes API, which is the only
# component here that does. The grant is a namespaced Role in `convertx` rather
# than a ClusterRole — see the comment at the top of prometheus-rbac.yaml.
echo ""
echo "▶ Step 12: Deploying monitoring and autoscaling..."

# metrics-server backs the HPAs applied in steps 8-9. Docker Desktop's kubelet
# serves its metrics endpoint with a self-signed cert that is not in the
# cluster CA, so --kubelet-insecure-tls is REQUIRED here or every scrape fails
# with "x509: cannot validate certificate" and the HPAs sit at <unknown>
# forever. That flag is a local-cluster concession; on real infrastructure the
# kubelet cert is properly signed and it must be dropped.
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml > /dev/null
kubectl patch deployment metrics-server -n kube-system --type=json \
  -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]' \
  > /dev/null 2>&1 || true

if kubectl rollout status deployment/metrics-server -n kube-system --timeout=120s > /dev/null 2>&1; then
  ok "metrics-server ready (HPAs can read CPU)"
else
  echo -e "  ${YELLOW}!${NC} metrics-server not ready — HPAs will report <unknown> and never scale"
  echo "     kubectl logs -n kube-system -l k8s-app=metrics-server --tail=30"
fi

kubectl apply -f infra/monitoring/prometheus-rbac.yaml > /dev/null
kubectl apply -f infra/monitoring/prometheus-configmap.yaml > /dev/null
kubectl apply -f infra/monitoring/prometheus-deployment.yaml > /dev/null

# Dashboards are generated from the JSON on disk rather than checked in as a
# ConfigMap, so the JSON stays the single source of truth — the same reason
# bootstrap.sh is built with --from-file in step 5.
kubectl create configmap grafana-dashboards \
  --from-file=infra/monitoring/dashboards/ \
  -n monitoring --dry-run=client -o yaml | kubectl apply -f - > /dev/null

kubectl apply -f infra/monitoring/grafana-config.yaml > /dev/null
kubectl apply -f infra/monitoring/grafana-deployment.yaml > /dev/null

# Neither Deployment rolls on a ConfigMap edit by itself.
kubectl rollout restart deployment/prometheus -n monitoring > /dev/null 2>&1 || true
kubectl rollout restart deployment/grafana -n monitoring > /dev/null 2>&1 || true

if kubectl rollout status deployment/prometheus -n monitoring --timeout=120s > /dev/null 2>&1; then
  ok "Prometheus running"
else
  echo -e "  ${YELLOW}!${NC} Prometheus not ready — no metrics will be collected"
  echo "     kubectl logs -n monitoring -l app=prometheus --tail=30"
fi

if kubectl rollout status deployment/grafana -n monitoring --timeout=120s > /dev/null 2>&1; then
  ok "Grafana provisioned with ConvertX dashboard"
else
  echo -e "  ${YELLOW}!${NC} Grafana not ready"
  echo "     kubectl logs -n monitoring -l app=grafana --tail=30"
fi

# ── Step 13: Port Forward ──────────────────────────────────────
echo ""
echo "▶ Step 13: Starting port forward..."
pkill -f "port-forward" 2>/dev/null || true
sleep 2

# KONG_SVC was resolved in step 3.
kubectl port-forward svc/$KONG_SVC 8080:80 -n kong > /dev/null 2>&1 &

# Grafana and Prometheus are reachable only this way: neither has an ingress
# nor a Kong route, which is what keeps the unauthenticated Grafana safe.
kubectl port-forward svc/grafana 3000:3000 -n monitoring > /dev/null 2>&1 &
kubectl port-forward svc/prometheus 9090:9090 -n monitoring > /dev/null 2>&1 &
sleep 3
ok "Port forwards active on localhost:8080 (api), :3000 (grafana), :9090 (prometheus)"

# ── Step 14: Health Checks ─────────────────────────────────────
echo ""
echo "▶ Step 14: Running health checks..."

AUTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
  http://localhost:8080/api/v1/auth/health)
CONV_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
  http://localhost:8080/api/v1/convert/health)

if [ "$AUTH_STATUS" = "200" ]; then
  ok "Auth Service:       $AUTH_STATUS"
else
  echo -e "  ${RED}✗${NC} Auth Service:       $AUTH_STATUS"
fi

if [ "$CONV_STATUS" = "200" ]; then
  ok "Conversion Service: $CONV_STATUS"
else
  echo -e "  ${RED}✗${NC} Conversion Service: $CONV_STATUS"
fi

# ── Done ───────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║         Setup Complete                   ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "  Gateway:     http://localhost:8080"
echo "  Auth API:    http://localhost:8080/api/v1/auth"
echo "  Convert API: http://localhost:8080/api/v1/convert"
echo "  Tools API:   http://localhost:8080/api/v1/tools"
echo ""
echo "  RDS:         $DB_ENDPOINT"
echo "  ElastiCache: $REDIS_ENDPOINT"
echo "  Log groups:  /convertx/auth-service  /convertx/conversion-service  /convertx/kong"
echo ""
echo "  Autoscaling: kubectl get hpa -n convertx -w"
echo ""
echo "  Grafana:     http://localhost:3000  (anonymous viewer; admin/admin to edit)"
echo "  Prometheus:  http://localhost:9090  (targets: /targets)"

CDN_DOMAIN=$(get_secret convertx/cloudfront/domain)
if [ -n "$CDN_DOMAIN" ]; then
  echo "  CloudFront:  $CDN_DOMAIN (origin $KONG_ORIGIN, caching disabled)"
fi
echo ""
echo "  Pods:"
kubectl get pods -n convertx
echo ""
kubectl get pods -n kong | grep -v "operator\|konnect"
echo ""
kubectl get pods -n localstack
echo ""
echo "  To stop port forward:  pkill -f port-forward"
echo "  To view auth logs:     kubectl logs -n convertx -l app=auth-service -f"
echo "  To view convert logs:  kubectl logs -n convertx -l app=conversion-service -f"
echo "  To read CloudWatch:    bash scripts/tail-logs.sh /convertx/kong"
echo "  To teardown:           bash teardown.sh"
echo ""
