apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: convertx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""                    # ← add this
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-pv